{
  "openapi": "3.0.1",
  "info": {
    "title": "Tokio marine api example",
    "version": "v1"
  },
  "paths": {
    "/todos": {
      "get": {
        "tags": [
          "TodoItems"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/TodoItemDTO"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "TodoItems"
        ],
        "requestBody": {
          "content": {
            "application/json-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/TodoItemDTO"
              },
              "example": {
                "name": "John Doe",
                "isComplete": true
              }
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TodoItemDTO"
              },
              "example": {
                "name": "John Doe",
                "isComplete": true
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/TodoItemDTO"
              },
              "example": {
                "name": "John Doe",
                "isComplete": true
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/TodoItemDTO"
              },
              "example": {
                "name": "John Doe",
                "isComplete": true
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TodoItemDTO"
                }
              }
            }
          }
        }
      }
    },
    "/todos/{id}": {
      "get": {
        "tags": [
          "TodoItems"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TodoItemDTO"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "TodoItems"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/TodoItem"
              },
              "example": {
                "id": 1,
                "name": "Updated name",
                "isComplete": false,
                "secret": null
              }
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TodoItem"
              },
              "example": {
                "id": 1,
                "name": "Updated name",
                "isComplete": false,
                "secret": null
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/TodoItem"
              },
              "example": {
                "id": 1,
                "name": "Updated name",
                "isComplete": false,
                "secret": null
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/TodoItem"
              },
              "example": {
                "id": 1,
                "name": "Updated name",
                "isComplete": false,
                "secret": null
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "patch": {
        "tags": [
          "TodoItems"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json-patch+json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Operation"
                }
              },
              "example": [
                {
                  "value": "Updated Name",
                  "path": "/Name",
                  "op": "replace"
                }
              ]
            },
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Operation"
                }
              },
              "example": [
                {
                  "value": "Updated Name",
                  "path": "/Name",
                  "op": "replace"
                }
              ]
            },
            "text/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Operation"
                }
              },
              "example": [
                {
                  "value": "Updated Name",
                  "path": "/Name",
                  "op": "replace"
                }
              ]
            },
            "application/*+json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Operation"
                }
              },
              "example": [
                {
                  "value": "Updated Name",
                  "path": "/Name",
                  "op": "replace"
                }
              ]
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "delete": {
        "tags": [
          "TodoItems"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Operation": {
        "type": "object",
        "properties": {
          "operationType": {
            "$ref": "#/components/schemas/OperationType"
          },
          "path": {
            "type": "string",
            "nullable": true
          },
          "op": {
            "type": "string",
            "nullable": true
          },
          "from": {
            "type": "string",
            "nullable": true
          },
          "value": {
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "OperationType": {
        "enum": [
          0,
          1,
          2,
          3,
          4,
          5,
          6
        ],
        "type": "integer",
        "format": "int32"
      },
      "TodoItem": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "name": {
            "type": "string",
            "nullable": true
          },
          "isComplete": {
            "type": "boolean"
          },
          "secret": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "TodoItemDTO": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "example": 1
          },
          "name": {
            "type": "string",
            "nullable": true,
            "example": "todo 1"
          },
          "isComplete": {
            "type": "boolean"
          }
        },
        "additionalProperties": false
      }
    }
  }
}